EXPERIMENT:
  NAME: ""
  TAG: "kd,wrn_40_2,MobileNetV2,2,9"
  PROJECT: "Fairness_Logit_Stand"
DISTILLER:
  TYPE: "KD"
  TEACHER: "wrn_40_2"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
