EXPERIMENT:
  NAME: "setting63_KD:EKD=3:6"
  TAG: "student_softplus,teacher_softplus"
  PROJECT: "resnet110_resnet32"
DISTILLER:
  TYPE: "KD4eModel"
  STUDENT: "resnet32"
  TEACHER: "resnet110"
EKD:
  WARMUP: 30
  STUDENT: 
    CLF_TYPE: "softplus"
    ACTIVATION: "relu"
    LAMB: -0.86
  TEACHER: 
    CLF_TYPE: "softplus"
    ACTIVATION: "relu"
    LAMB: -0.86
  LOSS:
    KL: False
    CE_WEIGHT: 5.0
    EKD_WEIGHT: 2.5
    KD_WEIGHT: 2.5
    EXPECTATION: False
    TEMPERATURE: 1
DKD:
  BETA: 2.0
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
