EXPERIMENT:
  NAME: ""
  TAG: "student_softplus,teacher_softplus"
  PROJECT: "search_all_weights"
DISTILLER:
  TYPE: "KD4eModel"
  STUDENT: "resnet8x4"
  TEACHER: "resnet32x4"
EKD:
  STUDENT: 
    CLF_TYPE: "softplus"
    ACTIVATION: "relu"
  TEACHER: 
    CLF_TYPE: "softplus"
    ACTIVATION: "relu"
    LAMB: -1.22
  LOSS:
    KL: False
    CE_WEIGHT: 0.1
    EKD_WEIGHT: 4.5
    KD_WEIGHT: 4.5
    EXPECTATION: False
    TEMPERATURE: 1
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [80, 150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
