EXPERIMENT:
  NAME: "setting63,KD:EKD=4.5:4.5,WARMUP=150"
  TAG: "student_softplus,teacher_softplus"
  PROJECT: "wrn_40_2_mnv2"
DISTILLER:
  TYPE: "KD4eModel"
  STUDENT: "MobileNetV2"
  TEACHER: "wrn_40_2"
EKD:
  WARMUP: 150
  STUDENT: 
    CLF_TYPE: "softplus"
    ACTIVATION: "relu"
    LAMB: -1.21
  TEACHER: 
    CLF_TYPE: "softplus"
    ACTIVATION: "relu"
    LAMB: -1.21
  LOSS:
    KL: False
    CE_WEIGHT: 1.0
    EKD_WEIGHT: 4.5
    KD_WEIGHT: 4.5
    EXPECTATION: False
    TEMPERATURE: 1
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
