MODEL:
  TYPE: DeiT
  NUM_CLASSES: 100
  LOSS_FUN: "evidential_cross_entropy"
  LAMB: -0.14
TRANSFORMER:
  PATCH_SIZE: 16
  HIDDEN_DIM: 192
  DEPTH: 12
  NUM_HEADS: 3
  MLP_RATIO: 4
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
LOG_WANDB: True
WANDB:
  PROJECT: "DeiT"
  NAME: "cls:kd:ekd=2:4:2,wamrup=1,T=1"
CNN:
  DEPTH: 56
RESNET:
  TRANS_FUN: basic_transform
DISTILLATION:
  ENABLE_LOGIT: True
  LOGIT_LOSS: "soft"
  LOGIT_TEMP: 1.0
  LOGIT_WEIGHT: 1.0
  KD_WEIGHT: 4.0
  EKD_WEIGHT: 2.0
  CLS_WEIGHT: 2.0
  ENABLE_EKD: True
  WARMUP: 1
  EXTRA_WEIGHT_IN: 10
  LOGIT_STANDARD: True
  TEACHER_MODEL: ResNet
  TEACHER_WEIGHTS: work_dirs/evidential-r-56_c100/model.pyth
  TEACHER_IMG_SIZE: 32
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
  AUTO_RESUME: False
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: False
CUDNN:
  BENCHMARK: False
