method: grid
metric:
  name: best_acc  # 选择要优化的衡量标准
  goal: maximize  # 目标是最小化该指标
parameters:
  KL:
    values: [False] # KL refers to the loss_kl
  CLF_TYPE:
    values: ["softmax","softplus"]
  ACTIVATION:
    values: ["gelu"]
  LAMB2:
    values: [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3]
