method: random
metric:
  name: best_acc  # 选择要优化的衡量标准
  goal: maximize  # 目标是最小化该指标
parameters:
  ce_weight: 
    values: [1.0]
  ekd_weight:
    min: 10
    max: 500
  student_clf:
    values: ["relu"]
  teacher_clf:
    values: ["softplus"]
  student_lamb:
    min: 0.1
    max: 3.0
  teacher_lamb:
    min: 0.1
    max: 3.0