method: grid
metric:
  name: best_acc  # 选择要优化的衡量标准
  goal: maximize  # 目标是最小化该指标
parameters:
  ce_weight: 
    values: [0.1, 0.3, 0.5, 0.7, 0.9, 1.0, 1.5, 2.0]
  ekd_weight:
    values: [0.3, 0.6, 0.9, 3, 6, 9, 30, 60, 90, 200]