EXPERIMENT:
  NAME: "0.1lr"
  TAG: "KD"
  PROJECT: "BKD"
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
