EXPERIMENT:
  NAME: "softmax_Teacher_VGG13"
  TAG: "softmax"
  PROJECT: "CIFAR10"
DATASET:
  TYPE: 'cifar10'
DISTILLER:
  TYPE: "NONE"
  STUDENT: "vgg13"
TEACHER:
  CLF_TYPE: "exp"
  KL: False
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
