EXPERIMENT:
  NAME: "Logit_Stand,vgg13,vgg8"
  TAG: "kd,vgg13,vgg8,2,9"
  PROJECT: "CIFAR10"
DATASET:
  TYPE: "cifar10"
DISTILLER:
  TYPE: "KD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
