EXPERIMENT:
  NAME: ""
  TAG: "resnet32x4"
  PROJECT: "cifar100_R-EDL_Teacher_ce_activ_clf_sweep"
DISTILLER:
  TYPE: Teacher
  STUDENT: "resnet32x4_exp"
  CLF_TYPE: "elu"
  ACTIVATION: "relu"
  LAMB1: 1.0
  LAMB2: 0.2
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
