EXPERIMENT:
  NAME: ""
  TAG: "resnet32x4"
  PROJECT: "cifar100_R-EDL_Teacher_activ_clf"
DISTILLER:
  TYPE: NONE
  STUDENT: "resnet32x4_exp"
  ACTIVATION: "relu"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
