EXPERIMENT:
  NAME: "softmax"
  TAG: "exp"
  PROJECT: "Student_ResNet32(226)"
DISTILLER:
  TYPE: "NONE"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
