EXPERIMENT:
  NAME: "softplus_teacher"
  TAG: "softplus"
  PROJECT: "cifar100_Teacher_search"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "resnet32x4_lamb"
  CLF_TYPE: "softplus"
  ACTIVATION: "relu"
  KL: False
  LAMB1: 1.0
  LAMB2: 0.3
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
