EXPERIMENT:
  NAME: "class_aware_lamb(seed1)"
  TAG: "softplus"
  PROJECT: "Teacher_ResNet56(226)"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "resnet56"
  CLF_TYPE: "exp"
  LAMB1: 1.0
  LAMB2: 3.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
