EXPERIMENT:
  NAME: "trained_lamb"
  TAG: "exp"
  PROJECT: "Student_SHN_V2(226)"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "ShuffleV2"
TEACHER:
  CLF_TYPE: "exp"
  LAMB: 0.0
  KL: False
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
