EXPERIMENT:
  NAME: "WRN_28-2"
  TAG: "softmax"
  PROJECT: "Teacher_WRN"
DATASET:
  TYPE: "cifar100"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "wrn_28_2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
