EXPERIMENT:
  NAME: "WRN_40_1"
  TAG: "exp"
  PROJECT: "Evidential_Student"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "wrn_40_1"
TEACHER: 
  CLF_TYPE: "exp"
  KL: False
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
