EXPERIMENT:
  NAME: "exp+0.2"
  TAG: "resnet8x4"
  PROJECT: "Student"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "resnet8x4"
  CLF_TYPE: "exp"
  ACTIVATION: "relu"
  KL: False
  LAMB1: 1.0
  LAMB2: 0.2
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
