EXPERIMENT:
  NAME: "resnet8x4_fc_bias"
  TAG: "resnet8x4,bias"
  PROJECT: "train_lamb"
DISTILLER:
  TYPE: "Teacher"
  STUDENT: "resnet8x4"
  CLF_TYPE: "exp"
  ACTIVATION: "relu"
  KL: False
  LAMB1: 1.0
SWEEP: 
  START: False
  num_agents: 7
  multiprocess: False
LOG:
  WANDB: True
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
