EXPERIMENT:
  NAME: "Studentonly"
  TAG: "edl,res50,mobilenetv2"
  PROJECT: "ImageNet_R34_MV2"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 64
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "Teacher"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
TEACHER:
  CLF_TYPE: "exp"
  LAMB: 0.0
  KL: False
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DKD:
  CE_WEIGHT: 1.0
  BETA: 2.0
  T: 1.0
  WARMUP: 1
